version: "3.4"
services:
  web:
    build: .
    container_name: microserviceapi
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py makemigrations measures_API && python manage.py migrate measures_API && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./apps:/code/apps
    ports:
      - "8000:8000"
    expose:
      - "8000"
    networks:
      - local-dev

networks:
  local-dev:
    external: true